[[louvain]]
arch = "aarch64"
git-tree-sha1 = "1ca726bc0568be0feac8eab13f1d46cd3b783835"
os = "macos"

    [[louvain.download]]
    sha256 = "f2bef1eba9bae74f19c40673a41ef0280d76aabf112c571fb2b0a88d59c33765"
    url = "https://github.com/JuliaBinaryWrappers/louvain_jll.jl/releases/download/louvain-v0.2.0+0/louvain.v0.2.0.aarch64-apple-darwin.tar.gz"
[[louvain]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "13f322685dac5bcdaea820a8b660c43d6f0565e3"
libc = "glibc"
os = "linux"

    [[louvain.download]]
    sha256 = "238a5cc48d042b108ce08b68a3f90ad59c8e0d6f9b1fe2bb73c1357a59751e87"
    url = "https://github.com/JuliaBinaryWrappers/louvain_jll.jl/releases/download/louvain-v0.2.0+0/louvain.v0.2.0.aarch64-linux-gnu-cxx03.tar.gz"
[[louvain]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f74b886418e0e63630e7db7b0d45c2c188d2f068"
libc = "glibc"
os = "linux"

    [[louvain.download]]
    sha256 = "e737e8b07aee331f1e708e33133726e1854c254c4fb0c935f83e3f79b9c03b40"
    url = "https://github.com/JuliaBinaryWrappers/louvain_jll.jl/releases/download/louvain-v0.2.0+0/louvain.v0.2.0.aarch64-linux-gnu-cxx11.tar.gz"
[[louvain]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4e74c6131a821869d2991b38c2d07bdcadbfc04d"
libc = "musl"
os = "linux"

    [[louvain.download]]
    sha256 = "84b0825a77ce75667300f3f42374a457185a06d87f975e519ab77c1d143a4899"
    url = "https://github.com/JuliaBinaryWrappers/louvain_jll.jl/releases/download/louvain-v0.2.0+0/louvain.v0.2.0.aarch64-linux-musl-cxx03.tar.gz"
[[louvain]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "307326a613aae531712faa597acd6ffe7bc547b6"
libc = "musl"
os = "linux"

    [[louvain.download]]
    sha256 = "d9380fb6abfa9be277c74436336ab097c95bad85d0f2a297dcde01e4fb1ae04f"
    url = "https://github.com/JuliaBinaryWrappers/louvain_jll.jl/releases/download/louvain-v0.2.0+0/louvain.v0.2.0.aarch64-linux-musl-cxx11.tar.gz"
[[louvain]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2e8722e21c8d82b89aab4bbcab2137d539e5e986"
libc = "glibc"
os = "linux"

    [[louvain.download]]
    sha256 = "adc2c40a0e258fe7f05e2e714fb89bd9f29bcfe7b0e88e356781e435010889de"
    url = "https://github.com/JuliaBinaryWrappers/louvain_jll.jl/releases/download/louvain-v0.2.0+0/louvain.v0.2.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[louvain]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2f220cb4021d223f4bf27259a6e049e0aad4f473"
libc = "glibc"
os = "linux"

    [[louvain.download]]
    sha256 = "b29639def42767b6971888c2d061faad3e7e9ad73a624f24b2b80d7ed78b0dfb"
    url = "https://github.com/JuliaBinaryWrappers/louvain_jll.jl/releases/download/louvain-v0.2.0+0/louvain.v0.2.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[louvain]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "58615e3b99008fbca54642837ae6dd05c9fd0d35"
libc = "musl"
os = "linux"

    [[louvain.download]]
    sha256 = "ade5cbf4283b401cb96aca167b57a18080aea99d419845dd2109341cad26edfa"
    url = "https://github.com/JuliaBinaryWrappers/louvain_jll.jl/releases/download/louvain-v0.2.0+0/louvain.v0.2.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[louvain]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "845a8edb3114487631ecf05141d3cbc74b254e86"
libc = "musl"
os = "linux"

    [[louvain.download]]
    sha256 = "bb5dea2360ca90d2e6206b210ebedf1aab9b4fbb338ccbc0a33fc0ed6bc64714"
    url = "https://github.com/JuliaBinaryWrappers/louvain_jll.jl/releases/download/louvain-v0.2.0+0/louvain.v0.2.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[louvain]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ac0948b29e6bbcf5507f11627b0778873729a531"
libc = "glibc"
os = "linux"

    [[louvain.download]]
    sha256 = "8c586010b6c4bcaef1487fad4b42696ec4274aef452b5d6347b601de7cd269e3"
    url = "https://github.com/JuliaBinaryWrappers/louvain_jll.jl/releases/download/louvain-v0.2.0+0/louvain.v0.2.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[louvain]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4ca634099bba68a67f67464cdbb683db5b55c9ec"
libc = "glibc"
os = "linux"

    [[louvain.download]]
    sha256 = "7aad26e779e8465803c1a79340fb6aad98a0188c574fd564084b5e9f95ae32ee"
    url = "https://github.com/JuliaBinaryWrappers/louvain_jll.jl/releases/download/louvain-v0.2.0+0/louvain.v0.2.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[louvain]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e997b8eb55d555186a6743243aa31ef608735b50"
libc = "musl"
os = "linux"

    [[louvain.download]]
    sha256 = "4896cdecc5ad81f5f419a151023985d3a8ab3bf2653a84ec99b647822d9c6579"
    url = "https://github.com/JuliaBinaryWrappers/louvain_jll.jl/releases/download/louvain-v0.2.0+0/louvain.v0.2.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[louvain]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "165e137dae2436edae2d55b189acf1244bd25f74"
libc = "musl"
os = "linux"

    [[louvain.download]]
    sha256 = "37ca6d48cb600c34f55082f4d5f90c83383984e36da4c651a10828a997389d34"
    url = "https://github.com/JuliaBinaryWrappers/louvain_jll.jl/releases/download/louvain-v0.2.0+0/louvain.v0.2.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[louvain]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "32d9659d8d7d6c74bd78b4eb5fc6986b05a254db"
libc = "glibc"
os = "linux"

    [[louvain.download]]
    sha256 = "346b4d92e2dda24d5fb781bb1177dafb558926c956b82948f2b5d02c4645a95c"
    url = "https://github.com/JuliaBinaryWrappers/louvain_jll.jl/releases/download/louvain-v0.2.0+0/louvain.v0.2.0.i686-linux-gnu-cxx03.tar.gz"
[[louvain]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e330f59aa5cdd008875c26fa6d4ee87ef211d2f0"
libc = "glibc"
os = "linux"

    [[louvain.download]]
    sha256 = "c030f4e0d64d88c1358806c143261aa9fd5b35da0ab577c91664ecffc992f0ac"
    url = "https://github.com/JuliaBinaryWrappers/louvain_jll.jl/releases/download/louvain-v0.2.0+0/louvain.v0.2.0.i686-linux-gnu-cxx11.tar.gz"
[[louvain]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "31e99b0c43ba2e336274b5068461e5ab0d34c6d0"
libc = "musl"
os = "linux"

    [[louvain.download]]
    sha256 = "3dd7d639809ee7ff06ffc367594c792d9c9a14ef1b98d908085bfa0664cefd6e"
    url = "https://github.com/JuliaBinaryWrappers/louvain_jll.jl/releases/download/louvain-v0.2.0+0/louvain.v0.2.0.i686-linux-musl-cxx03.tar.gz"
[[louvain]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d0dc7e2a7521d54e5b2577612423b0094dcd20a6"
libc = "musl"
os = "linux"

    [[louvain.download]]
    sha256 = "f50c0e271f1423c716685399471d3dbc84e13132e3272f26b92b5e682f344e56"
    url = "https://github.com/JuliaBinaryWrappers/louvain_jll.jl/releases/download/louvain-v0.2.0+0/louvain.v0.2.0.i686-linux-musl-cxx11.tar.gz"
[[louvain]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8c8acb4314956da9c8a358cf75f5644bfd859fd8"
os = "windows"

    [[louvain.download]]
    sha256 = "c1120b9657802bf0ef2a704adf4675ec98f97ff7993bb1834d898f00750fc25b"
    url = "https://github.com/JuliaBinaryWrappers/louvain_jll.jl/releases/download/louvain-v0.2.0+0/louvain.v0.2.0.i686-w64-mingw32-cxx03.tar.gz"
[[louvain]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cc24604e8476aeed24582d786f021e80c5d60fa6"
os = "windows"

    [[louvain.download]]
    sha256 = "92228b78ce3110e4e9a51135146d6f83aeacb64f0c6e9a74041b858cac84ab63"
    url = "https://github.com/JuliaBinaryWrappers/louvain_jll.jl/releases/download/louvain-v0.2.0+0/louvain.v0.2.0.i686-w64-mingw32-cxx11.tar.gz"
[[louvain]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7c22a18000c8889c1ce4e21244566dbf9dfc69ee"
libc = "glibc"
os = "linux"

    [[louvain.download]]
    sha256 = "fb7e1cb5f4eb55b1dbcd8bf977b3cfc5336ad466469d1819287fde9cc67b1ef9"
    url = "https://github.com/JuliaBinaryWrappers/louvain_jll.jl/releases/download/louvain-v0.2.0+0/louvain.v0.2.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[louvain]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "efb5a1573562c9ace80ef5a640f9045576560c17"
libc = "glibc"
os = "linux"

    [[louvain.download]]
    sha256 = "45f31ad40ac34602e689691e8cbbe009560f2500c9bb7209467af040e95c373e"
    url = "https://github.com/JuliaBinaryWrappers/louvain_jll.jl/releases/download/louvain-v0.2.0+0/louvain.v0.2.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[louvain]]
arch = "x86_64"
git-tree-sha1 = "0fb54ab4843f381b553a3115e23e9851f945d9ac"
os = "macos"

    [[louvain.download]]
    sha256 = "3840a5b8015a012e3973166885eceb9a020c4b83909c626e819acaaebdf10b1d"
    url = "https://github.com/JuliaBinaryWrappers/louvain_jll.jl/releases/download/louvain-v0.2.0+0/louvain.v0.2.0.x86_64-apple-darwin.tar.gz"
[[louvain]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "904c7dbbeedc8bc493d1a4aa26632c15284d9979"
libc = "glibc"
os = "linux"

    [[louvain.download]]
    sha256 = "cb76ac11b5f82f48f0540c07611c356ee0db4459d2530bb6d3a2e788eedf309c"
    url = "https://github.com/JuliaBinaryWrappers/louvain_jll.jl/releases/download/louvain-v0.2.0+0/louvain.v0.2.0.x86_64-linux-gnu-cxx03.tar.gz"
[[louvain]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8b202fa6034d6ac24d6dbc4ab1929212784dbcaf"
libc = "glibc"
os = "linux"

    [[louvain.download]]
    sha256 = "e0fb1f4d063c0f792d99b0b39fdd5a41e4f9028166e4f62fab85fac229ba4710"
    url = "https://github.com/JuliaBinaryWrappers/louvain_jll.jl/releases/download/louvain-v0.2.0+0/louvain.v0.2.0.x86_64-linux-gnu-cxx11.tar.gz"
[[louvain]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "48c288a21247d2e8928b36a35b41daa314210b3f"
libc = "musl"
os = "linux"

    [[louvain.download]]
    sha256 = "20b081081052788a5dd7a9f6c3fbdff3d666a84ab9eda16b824487fa9b6dd598"
    url = "https://github.com/JuliaBinaryWrappers/louvain_jll.jl/releases/download/louvain-v0.2.0+0/louvain.v0.2.0.x86_64-linux-musl-cxx03.tar.gz"
[[louvain]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "309dff320fb479a99ea7827d8f770178992ea7b4"
libc = "musl"
os = "linux"

    [[louvain.download]]
    sha256 = "707d64b4cbe6f44d2f561513946ad87e15eb05395b402bddbecfa0758f486ec7"
    url = "https://github.com/JuliaBinaryWrappers/louvain_jll.jl/releases/download/louvain-v0.2.0+0/louvain.v0.2.0.x86_64-linux-musl-cxx11.tar.gz"
[[louvain]]
arch = "x86_64"
git-tree-sha1 = "a337b31dcd408f498548de26a65fb5380582e600"
os = "freebsd"

    [[louvain.download]]
    sha256 = "cc92b041ee92444b39ffb39ea5ad666bbf9596facc06b239fcf99253fecf2dc0"
    url = "https://github.com/JuliaBinaryWrappers/louvain_jll.jl/releases/download/louvain-v0.2.0+0/louvain.v0.2.0.x86_64-unknown-freebsd.tar.gz"
[[louvain]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "59cafaf7e043c65c8da10c04e5fb42889836c214"
os = "windows"

    [[louvain.download]]
    sha256 = "62a29f6b4cf6cd21089b0c929c91a0e775ea0ee584c1bc3962908f4569658038"
    url = "https://github.com/JuliaBinaryWrappers/louvain_jll.jl/releases/download/louvain-v0.2.0+0/louvain.v0.2.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[louvain]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "855b9e5e34cb40517817baec13da355f81e777f8"
os = "windows"

    [[louvain.download]]
    sha256 = "6322219f2091d1e88ce4a0dbf8e77cc39156587d30897f474c73ba2ba4bc8483"
    url = "https://github.com/JuliaBinaryWrappers/louvain_jll.jl/releases/download/louvain-v0.2.0+0/louvain.v0.2.0.x86_64-w64-mingw32-cxx11.tar.gz"
